<option value="Animal Welfare">Animal Welfare</option>
<option value="Child Protection">Child Protection</option>
<option value="Climate Action">Climate Action</option>
<option value="Peace and Reconciliation">Peace and Reconciliation</option>
<option value="Disaster Response">Disaster Response</option>
<option value="Economic Growth">Economic Growth</option>
<option value="Education">Education</option>
<option value="Ecosystem Restoration">Ecosystem Restoration</option>
<option value="Gender Equality">Gender Equality</option>
<option value="Physical Health">Physical Health</option>
<option value="Ending Human Trafficking">Ending Human Trafficking</option>
<option value="Justice and Human Rights">Justice and Human Rights</option>
<option value="Sport">Sport</option>
<option value="Digital Literacy">Digital Literacy</option>
<option value="Food Security">Food Security</option>
<option value="Arts and Culture">Arts and Culture</option>
<option value="LGBTQIA+ Equality">LGBTQIA+ Equality</option>
<option value="COVID-19">COVID-19</option>
